# Generated by Django 5.0.4 on 2024-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('ipv6', models.GenericIPAddressField(null=True, protocol='IPv6', unique=True)),
                ('mac', models.CharField(max_length=17, null=True, unique=True)),
                ('os', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
