# Generated by Django 5.0.4 on 2024-04-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgazer', '0002_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netgazer.device'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netgazer.interface'),
        ),
    ]
