# Generated by Django 5.0.4 on 2024-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgazer', '0004_alter_device_ipv4_alter_device_ipv6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ipv4',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ipv6',
            field=models.GenericIPAddressField(null=True, protocol='IPv6', unique=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='ipv4',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='ipv6',
            field=models.GenericIPAddressField(null=True, protocol='IPv6'),
        ),
    ]
