# Generated by Django 5.0.4 on 2024-04-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgazer', '0006_neighbor'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='netgazer.device'),
            preserve_default=False,
        ),
    ]
