# Generated by Django 5.0.4 on 2024-04-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgazer', '0007_neighbor_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='neighbor_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_device', to='netgazer.device'),
        ),
    ]
