# Generated by Django 4.2.11 on 2024-04-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgazer', '0009_device_created_at_device_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ipv4',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ipv6',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mac',
        ),
        migrations.AddField(
            model_name='device',
            name='run_id',
            field=models.UUIDField(default='9af4e9a7-c367-467d-bb8c-33ed1425ee8b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interface',
            name='ipv4_mask',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='ipv6_mask',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
