# Generated by Django 4.2.11 on 2024-05-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgazer', '0011_device_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='physical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='protocol',
            field=models.BooleanField(default=False),
        ),
    ]
