# Generated by Django 4.2.11 on 2024-06-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netgazer', '0012_interface_physical_interface_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='port_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
